name: Test actions/setup-java

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Print gradle properties
        run: |
          ls ~/.gradle
          cat ~/.gradle/gradle.properties

